version: "3"

services:
  opengrok:
    build: opengrok
    container_name: ruby-opengrok
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./opengrok/src:/src

volumes:
  data:
